//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ColorDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class ColorDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeloDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class ModeloDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DenominacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ObjetivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Denominacion {
            get {
                return this.DenominacionField;
            }
            set {
                if ((object.ReferenceEquals(this.DenominacionField, value) != true)) {
                    this.DenominacionField = value;
                    this.RaisePropertyChanged("Denominacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Objetivo {
            get {
                return this.ObjetivoField;
            }
            set {
                if ((this.ObjetivoField.Equals(value) != true)) {
                    this.ObjetivoField = value;
                    this.RaisePropertyChanged("Objetivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sku {
            get {
                return this.SkuField;
            }
            set {
                if ((object.ReferenceEquals(this.SkuField, value) != true)) {
                    this.SkuField = value;
                    this.RaisePropertyChanged("Sku");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LineaDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class LineaDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspecificacionDeDefectoDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class EspecificacionDeDefectoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoDefectoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDefecto {
            get {
                return this.TipoDefectoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoDefectoField, value) != true)) {
                    this.TipoDefectoField = value;
                    this.RaisePropertyChanged("TipoDefecto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnoDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class TurnoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] HorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin {
            get {
                return this.FinField;
            }
            set {
                if ((this.FinField.Equals(value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Horas {
            get {
                return this.HorasField;
            }
            set {
                if ((object.ReferenceEquals(this.HorasField, value) != true)) {
                    this.HorasField = value;
                    this.RaisePropertyChanged("Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmpleadoDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class EmpleadoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasenia {
            get {
                return this.ContraseniaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseniaField, value) != true)) {
                    this.ContraseniaField = value;
                    this.RaisePropertyChanged("Contrasenia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((this.DocumentoField.Equals(value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OpDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class OpDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto[] DefectosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto[] HorariosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto LineaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto ModeloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto[] ParesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto[] Defectos {
            get {
                return this.DefectosField;
            }
            set {
                if ((object.ReferenceEquals(this.DefectosField, value) != true)) {
                    this.DefectosField = value;
                    this.RaisePropertyChanged("Defectos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFin {
            get {
                return this.FechaFinField;
            }
            set {
                if ((this.FechaFinField.Equals(value) != true)) {
                    this.FechaFinField = value;
                    this.RaisePropertyChanged("FechaFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaInicio {
            get {
                return this.FechaInicioField;
            }
            set {
                if ((this.FechaInicioField.Equals(value) != true)) {
                    this.FechaInicioField = value;
                    this.RaisePropertyChanged("FechaInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto[] Horarios {
            get {
                return this.HorariosField;
            }
            set {
                if ((object.ReferenceEquals(this.HorariosField, value) != true)) {
                    this.HorariosField = value;
                    this.RaisePropertyChanged("Horarios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto Linea {
            get {
                return this.LineaField;
            }
            set {
                if ((object.ReferenceEquals(this.LineaField, value) != true)) {
                    this.LineaField = value;
                    this.RaisePropertyChanged("Linea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto Modelo {
            get {
                return this.ModeloField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeloField, value) != true)) {
                    this.ModeloField = value;
                    this.RaisePropertyChanged("Modelo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto[] Pares {
            get {
                return this.ParesField;
            }
            set {
                if ((object.ReferenceEquals(this.ParesField, value) != true)) {
                    this.ParesField = value;
                    this.RaisePropertyChanged("Pares");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DefectoDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class DefectoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto EspecificacionDeDefectoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PieField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto EspecificacionDeDefecto {
            get {
                return this.EspecificacionDeDefectoField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecificacionDeDefectoField, value) != true)) {
                    this.EspecificacionDeDefectoField = value;
                    this.RaisePropertyChanged("EspecificacionDeDefecto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((this.HoraField.Equals(value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pie {
            get {
                return this.PieField;
            }
            set {
                if ((object.ReferenceEquals(this.PieField, value) != true)) {
                    this.PieField = value;
                    this.RaisePropertyChanged("Pie");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HorarioDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class HorarioDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto[] DefectosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto[] ParesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto[] Defectos {
            get {
                return this.DefectosField;
            }
            set {
                if ((object.ReferenceEquals(this.DefectosField, value) != true)) {
                    this.DefectosField = value;
                    this.RaisePropertyChanged("Defectos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fin {
            get {
                return this.FinField;
            }
            set {
                if ((this.FinField.Equals(value) != true)) {
                    this.FinField = value;
                    this.RaisePropertyChanged("Fin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Inicio {
            get {
                return this.InicioField;
            }
            set {
                if ((this.InicioField.Equals(value) != true)) {
                    this.InicioField = value;
                    this.RaisePropertyChanged("Inicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto[] Pares {
            get {
                return this.ParesField;
            }
            set {
                if ((object.ReferenceEquals(this.ParesField, value) != true)) {
                    this.ParesField = value;
                    this.RaisePropertyChanged("Pares");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParDto", Namespace="http://schemas.datacontract.org/2004/07/ControlCalidad.Servidor.Servicio")]
    [System.SerializableAttribute()]
    public partial class ParDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string calidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string calidad {
            get {
                return this.calidadField;
            }
            set {
                if ((object.ReferenceEquals(this.calidadField, value) != true)) {
                    this.calidadField = value;
                    this.RaisePropertyChanged("calidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlCalidadServiceReference.IControlCalidadServicio")]
    public interface IControlCalidadServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/RegistrarDefecto", ReplyAction="http://tempuri.org/IControlCalidadServicio/RegistrarDefectoResponse")]
        bool RegistrarDefecto(int idEspDefecto, int numero, string pie, int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/RegistrarDefecto", ReplyAction="http://tempuri.org/IControlCalidadServicio/RegistrarDefectoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarDefectoAsync(int idEspDefecto, int numero, string pie, int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/RegistrarPar", ReplyAction="http://tempuri.org/IControlCalidadServicio/RegistrarParResponse")]
        bool RegistrarPar(int numero, string calidad, int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/RegistrarPar", ReplyAction="http://tempuri.org/IControlCalidadServicio/RegistrarParResponse")]
        System.Threading.Tasks.Task<bool> RegistrarParAsync(int numero, string calidad, int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/InicializarOp", ReplyAction="http://tempuri.org/IControlCalidadServicio/InicializarOpResponse")]
        System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto[]> InicializarOp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/InicializarOp", ReplyAction="http://tempuri.org/IControlCalidadServicio/InicializarOpResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto[]>> InicializarOpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ConfirmarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/ConfirmarOPResponse")]
        System.ValueTuple<bool, string> ConfirmarOP(int numero, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto linea, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto modelo, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ConfirmarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/ConfirmarOPResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> ConfirmarOPAsync(int numero, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto linea, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto modelo, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/GetEspecificacionDeDefectoTipo", ReplyAction="http://tempuri.org/IControlCalidadServicio/GetEspecificacionDeDefectoTipoResponse" +
            "")]
        ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto[] GetEspecificacionDeDefectoTipo(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/GetEspecificacionDeDefectoTipo", ReplyAction="http://tempuri.org/IControlCalidadServicio/GetEspecificacionDeDefectoTipoResponse" +
            "")]
        System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto[]> GetEspecificacionDeDefectoTipoAsync(string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ObtenerDatosDeTurnoActual", ReplyAction="http://tempuri.org/IControlCalidadServicio/ObtenerDatosDeTurnoActualResponse")]
        ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.TurnoDto ObtenerDatosDeTurnoActual(int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ObtenerDatosDeTurnoActual", ReplyAction="http://tempuri.org/IControlCalidadServicio/ObtenerDatosDeTurnoActualResponse")]
        System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.TurnoDto> ObtenerDatosDeTurnoActualAsync(int numeroOP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/IniciarSesion", ReplyAction="http://tempuri.org/IControlCalidadServicio/IniciarSesionResponse")]
        System.ValueTuple<bool, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EmpleadoDto> IniciarSesion(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/IniciarSesion", ReplyAction="http://tempuri.org/IControlCalidadServicio/IniciarSesionResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EmpleadoDto>> IniciarSesionAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/GetOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/GetOPResponse")]
        ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto GetOP(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/GetOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/GetOPResponse")]
        System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto> GetOPAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/PausarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/PausarOPResponse")]
        bool PausarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/PausarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/PausarOPResponse")]
        System.Threading.Tasks.Task<bool> PausarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ReanudarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/ReanudarOPResponse")]
        System.ValueTuple<bool, string> ReanudarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/ReanudarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/ReanudarOPResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string>> ReanudarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/FinalizarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/FinalizarOPResponse")]
        bool FinalizarOP(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/FinalizarOP", ReplyAction="http://tempuri.org/IControlCalidadServicio/FinalizarOPResponse")]
        System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/AsignarOPaSupervisorDeCalidad", ReplyAction="http://tempuri.org/IControlCalidadServicio/AsignarOPaSupervisorDeCalidadResponse")]
        ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto AsignarOPaSupervisorDeCalidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/AsignarOPaSupervisorDeCalidad", ReplyAction="http://tempuri.org/IControlCalidadServicio/AsignarOPaSupervisorDeCalidadResponse")]
        System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto> AsignarOPaSupervisorDeCalidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/auxiliar", ReplyAction="http://tempuri.org/IControlCalidadServicio/auxiliarResponse")]
        System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto> auxiliar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IControlCalidadServicio/auxiliar", ReplyAction="http://tempuri.org/IControlCalidadServicio/auxiliarResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto>> auxiliarAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IControlCalidadServicioChannel : ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.IControlCalidadServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ControlCalidadServicioClient : System.ServiceModel.ClientBase<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.IControlCalidadServicio>, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.IControlCalidadServicio {
        
        public ControlCalidadServicioClient() {
        }
        
        public ControlCalidadServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ControlCalidadServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlCalidadServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ControlCalidadServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RegistrarDefecto(int idEspDefecto, int numero, string pie, int numeroOP) {
            return base.Channel.RegistrarDefecto(idEspDefecto, numero, pie, numeroOP);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarDefectoAsync(int idEspDefecto, int numero, string pie, int numeroOP) {
            return base.Channel.RegistrarDefectoAsync(idEspDefecto, numero, pie, numeroOP);
        }
        
        public bool RegistrarPar(int numero, string calidad, int numeroOP) {
            return base.Channel.RegistrarPar(numero, calidad, numeroOP);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarParAsync(int numero, string calidad, int numeroOP) {
            return base.Channel.RegistrarParAsync(numero, calidad, numeroOP);
        }
        
        public System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto[]> InicializarOp() {
            return base.Channel.InicializarOp();
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto[], ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto[]>> InicializarOpAsync() {
            return base.Channel.InicializarOpAsync();
        }
        
        public System.ValueTuple<bool, string> ConfirmarOP(int numero, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto linea, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto modelo, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto color) {
            return base.Channel.ConfirmarOP(numero, linea, modelo, color);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> ConfirmarOPAsync(int numero, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.LineaDto linea, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ModeloDto modelo, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ColorDto color) {
            return base.Channel.ConfirmarOPAsync(numero, linea, modelo, color);
        }
        
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto[] GetEspecificacionDeDefectoTipo(string tipo) {
            return base.Channel.GetEspecificacionDeDefectoTipo(tipo);
        }
        
        public System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EspecificacionDeDefectoDto[]> GetEspecificacionDeDefectoTipoAsync(string tipo) {
            return base.Channel.GetEspecificacionDeDefectoTipoAsync(tipo);
        }
        
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.TurnoDto ObtenerDatosDeTurnoActual(int numeroOP) {
            return base.Channel.ObtenerDatosDeTurnoActual(numeroOP);
        }
        
        public System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.TurnoDto> ObtenerDatosDeTurnoActualAsync(int numeroOP) {
            return base.Channel.ObtenerDatosDeTurnoActualAsync(numeroOP);
        }
        
        public System.ValueTuple<bool, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EmpleadoDto> IniciarSesion(string usuario, string password) {
            return base.Channel.IniciarSesion(usuario, password);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.EmpleadoDto>> IniciarSesionAsync(string usuario, string password) {
            return base.Channel.IniciarSesionAsync(usuario, password);
        }
        
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto GetOP(string usuario) {
            return base.Channel.GetOP(usuario);
        }
        
        public System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto> GetOPAsync(string usuario) {
            return base.Channel.GetOPAsync(usuario);
        }
        
        public bool PausarOP(int numero) {
            return base.Channel.PausarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> PausarOPAsync(int numero) {
            return base.Channel.PausarOPAsync(numero);
        }
        
        public System.ValueTuple<bool, string> ReanudarOP(int numero) {
            return base.Channel.ReanudarOP(numero);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string>> ReanudarOPAsync(int numero) {
            return base.Channel.ReanudarOPAsync(numero);
        }
        
        public bool FinalizarOP(int numero) {
            return base.Channel.FinalizarOP(numero);
        }
        
        public System.Threading.Tasks.Task<bool> FinalizarOPAsync(int numero) {
            return base.Channel.FinalizarOPAsync(numero);
        }
        
        public ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto AsignarOPaSupervisorDeCalidad() {
            return base.Channel.AsignarOPaSupervisorDeCalidad();
        }
        
        public System.Threading.Tasks.Task<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.OpDto> AsignarOPaSupervisorDeCalidadAsync() {
            return base.Channel.AsignarOPaSupervisorDeCalidadAsync();
        }
        
        public System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto> auxiliar() {
            return base.Channel.auxiliar();
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.HorarioDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.DefectoDto, ControlCalidad.Cliente.AccesoExterno.ControlCalidadServiceReference.ParDto>> auxiliarAsync() {
            return base.Channel.auxiliarAsync();
        }
    }
}
