// <auto-generated />
namespace ControlCalidad.Servidor.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IncioDeSesion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncioDeSesion));
        
        string IMigrationMetadata.Id
        {
            get { return "202012162144197_IncioDeSesion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
